# Generated by Django 5.2.8 on 2025-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_farmer_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supplier_approved',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
